### ISSUE TITLE
Required C++ Standard

### ISSUE THREAD

**Issue by pauleonix** [mbeutel/makeshift#6]
The headers `makeshift/variant.hpp` and `makeshift/metadata.hpp` (maybe more) require C++17 (see e.g. [here](https://github.com/mbeutel/makeshift/blob/master/include/makeshift/variant.hpp#L9), but the `src/CMakeLists.txt` defines the interface to only require C++14 (see [here](https://github.com/mbeutel/makeshift/blob/master/src/CMakeLists.txt#L14)).

**Comment by mbeutel** [comment]
That's correct. I had made quite some effort to keep this library on C++14 because I wanted to support NVCC, which back then didn't support C++17. But obviously C++14 wouldn't do for anything `variant<>`-related. One could say we have partial support for C++14 with some header files having additional requirements.

I plan to drop C++14 support for the next major version.
